# Generated by Django 6.0.3 on 2026-04-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('cup', 'Cup'), ('glass', 'Glass')], default='piece', max_length=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('expiry_days', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='products/default.jpg', upload_to='products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('suggestions', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
