# Generated by Django 6.0.3 on 2026-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product features like weight, brand, etc.', null=True),
        ),
    ]
