# Generated by Django 6.0.3 on 2026-04-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('500g', '500Grams'), ('250g', '250 Grams'), ('piece', 'Piece'), ('cup', 'Cup'), ('glass', 'Glass')], default='piece', max_length=10),
        ),
    ]
