# Generated by Django 6.0.3 on 2026-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('1kg', '1 kg'), ('500g', '500Grams'), ('50g', '50 Grams'), ('250g', '250Grams'), ('5kg', '5killograms'), ('piece', 'Piece'), ('cup', 'Cup'), ('glass', 'Glass'), ('1 Unit', '1 Unit'), ('220 ml', '220 ML')], default='piece', max_length=10),
        ),
    ]
